---
- name: extract mirrormaker jars
  unarchive:
    src: "/sysadm/lib/software/kafka/kafka-mirror-maker-core-0.1.3.tgz"
    dest: "/{{ env }}/lib/sft/kafka"
    creates: "/{{ env }}/lib/sft/kafka/mirror-maker"
  become: yes
  become_user: "{{ env_prefix }}kafka"
  when: "'machineA' in group_names"

- name: create needed kafka topics
  shell: /{{ env }}/lib/ctl/kfkcrp/bin/kfkcrp_topics.sh -a SYNC
  become: true
  become_user: "{{ usr }}"

- name: create systemd service for kafka mirrormaker
  template:
    src: "{{ kafka_mirrormaker_template }}"
    dest: "/usr/lib/systemd/system/{{ prj }}-mirrormaker.service"
    mode: 0644

- name: enable and start kafka mirrormaker systemd service
  systemd:
    name: "{{ prj }}-mirrormaker"
    daemon_reload: yes
    state: started
    enabled: true

